# General pipeline settings
working_directory: /home/shoerl/my_working_directory

# Requested stages
run:
  - nyc_taxi.show

config:
  years: [2018]
  months: [1, 2, 3]
  base_url: https://s3.amazonaws.com/nyc-tlc/trip+data
