on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        with:
          release-type: python
          token: "${{ secrets.RELEASE }}"
      - uses: actions/checkout@v7
        if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-python@v6
        if: ${{ steps.release.outputs.release_created }}
        with:
          python-version: "3.10"
      - name: Publish
        if: ${{ steps.release.outputs.release_created }}
        run: |
          pip install --upgrade build twine
          python -m build
          python3 -m twine upload -u  -p ${{ secrets.PYPI }} dist/*
