name: Unit tests

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9.7
      - run: |
          python -m pip install --upgrade pip
          pip install -r requirements-dev.txt
          pip install .
      - run: |
          python -m pytest tests
